### ISSUE TITLE
Infografía Ciclo de vida de un Sistema- Edwin López Santiago

### ISSUE THREAD

**Issue by Edwin14459** [SistemasTecTlaxiaco/actividad-1-infografia-Edwin14459#2]
[Infografía Ciclo de vida de un Sistema - Edwin López Santiago.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Edwin14459/files/12490861/Infografia.Ciclo.de.vida.de.un.Sistema.-.Edwin.Lopez.Santiago.pdf)

**Comment by saul19bautista** [comment]
Buena interpretación, y coherencia en todo.
👍👍👍👍
Calificación 19.4

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
